-- MySQL Script generated by MySQL Workbench
-- qua 04 dez 2024 11:23:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aluno` ;

CREATE TABLE IF NOT EXISTS `aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `matricula` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_aluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materia` ;

CREATE TABLE IF NOT EXISTS `materia` (
  `codigo` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `carga_horaria` VARCHAR(255) NOT NULL,
  `pre_requisitos` VARCHAR(255) NULL,
  `co_requisitos` VARCHAR(255) NULL,
  `periodo` VARCHAR(255) NOT NULL,
  `local` VARCHAR(255) NULL,
  `horario` VARCHAR(255) NOT NULL,
  `componente` VARCHAR(255) NOT NULL,
  `id_professor` INT NOT NULL,
  PRIMARY KEY (`codigo`, `id_professor`),
  INDEX `fk_materia_professor1_idx` (`id_professor` ASC) VISIBLE,
  CONSTRAINT `fk_materia_professor`
    FOREIGN KEY (`id_professor`)
    REFERENCES `professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matriculas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matriculas` ;

CREATE TABLE IF NOT EXISTS `matriculas` (
  `id_matricula` INT NOT NULL,
  `fk_id_aluno` INT NOT NULL,
  `id_matricula` VARCHAR(255) NOT NULL,
  `data_cadastro` VARCHAR(45) NOT NULL,
  INDEX `fk_codigo_materia_idx` (`id_matricula` ASC) VISIBLE,
  PRIMARY KEY (`id_matricula`),
  CONSTRAINT `fk_id_aluno`
    FOREIGN KEY (`fk_id_aluno`)
    REFERENCES `aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_codigo_materia`
    FOREIGN KEY (`id_matricula`)
    REFERENCES `materia` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `professor` ;

CREATE TABLE IF NOT EXISTS `professor` (
  `id_professor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `ingresso` VARCHAR(255) NOT NULL,
  `vinculo` VARCHAR(255) NOT NULL,
  `emil` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_professor`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
